module.exports = {
    script: function(context, _content, partial, slot, options) {
        var out = [];
        out.push("/*\n");
        out.push(" * autogenerated\n");
        out.push(" * {comment}\n");
        out.push(" */\n");
        out.push("Ext.directFn({\n");
        out.push("  namespace: \"" + (context.namespace) + "\",\n");
        out.push("  name: '" + (context.name) + "',");
        if (context.formHandler) {
            out.push("\n");
            out.push("  extension: {\n");
            out.push("    formHandler: true\n");
            out.push("  },");
        }
        out.push("\n");
        out.push("  locationType: \"" + (context.locationType) + "\",\n");
        out.push("  body: function(para){" + (context.body) + "}\n");
        out.push("});\n");
        out.push("/*\n");
        out.push(" * end autogenerated\n");
        out.push(" */");
        return out.join('');
    },
    compile: function() {},
    dependency: {}
};

//# sourceMappingURL=generators/server/Meta.Direct/ext.directfn.njs.js.map