<#@ noContent #>
/*
 * autogenerated
 * {comment}
 */
Ext.directFn({
  namespace: "#{context.namespace}",
  name: '#{context.name}',
<#- if(context.formHandler) {#>
  extension: {
    formHandler: true
  },
<#-}#>
  locationType: "#{context.locationType}",
  body: function(para){#{context.body}}
});
/*
 * end autogenerated
 */