global.browser = false
export { TemplateFactory as Factory } from './TemplateFactory'
export { Template } from './Template'
export { compileLight } from '../common/utils/compileLight'
export { compileFull } from '../common/utils/compileFull'
export { Parser } from '../parser/parse'
export { run } from '../common/utils/run'
export { compileTs } from '../common/utils/compileTs'
export { parseFile } from '../common/utils/parseFile'
export { parse } from './parse'
export { TemplateBase } from '../common/types/TemplateBase'
